spring:
  application:
    name: eureka-service
  cloud:
    gateway:
      routes:
      - id: db-service
        uri: http://localhost/8300
        predicates:
        - Path=/db-service/{segment}
      - id: stock-service
        uri: http://localhost/8301
        predicates:
          - Path=/stock-service/{segment}

server:
  port: 8302

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
